### ISSUE TITLE
建议把 .idea 文件夹从 git 上传文件列表中删除

### ISSUE THREAD

**Issue by geniusjoe** [Gu1meter8/palmprint-recognition#1]
.idea 文件一般是 jetbrains 自带的配置文件，其他用户使用 jetbrains 打开后会默认使用  .idea  中的配置，建议把 .idea 文件夹从 git 上传文件列表中删除
另 我们哈深本科图像识别也把这个掌纹识别当作业了

**Comment by geniusjoe** [comment]
还有 __pycache__ 文件也是

**Comment by Gu1meter8** [comment]
好的，等我把最近手头的事忙完就开始整理下仓库
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhou zhuohan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月13日(星期六) 晚上7:33
收件人:&nbsp;"Gu1meter8/palmprint-recognition"<palmprint-recognition@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Gu1meter8/palmprint-recognition] 建议把 .idea 文件夹从 git 上传文件列表中删除 (#1)





 
.idea 文件一般是 jetbrains 自带的配置文件，其他用户使用 jetbrains 打开后会默认使用  .idea  中的配置，建议把 .idea 文件夹从 git 上传文件列表中删除
 另 我们哈深本科图像识别也把这个掌纹识别当作业了
